### ISSUE TITLE
Register sensor failed

### ISSUE THREAD

**Issue by danji90** [istSOS/istsos2#34]
Hello,
I am trying to use istSOS2 in a research project about sensor web standards and protocols. My problem is I can't register a new procedure once after having set up everything following the [tutorial](http://istsos.org/en/latest/doc/index.html).

I have dockerised istSOS using the [installation guide](http://istsos.org/en/latest/doc/installation.html), which, as mentioned by [SunveerSingh ](https://github.com/SunveerSingh) in issue #33, needs to be updated (e.g. the wns folder referred to in the installation guide it seems has been renamed to wnslib). I adapted the steps slightly to the newest istSOS2 stable version (2.3.1)

My Dockerfile looks like...

========================================
```
FROM ubuntu:14.04

RUN apt-get update \
                && apt-get install -y --no-install-recommends apache2 libapache2-mod-wsgi python-psycopg2

COPY ./istsos-2.3.1.tar.gz .

RUN tar -zxvf ./istsos-2.3.1.tar.gz -C /usr/local/ \
                && chmod 755 -R /usr/local/istsos \
                && chown -R www-data:www-data /usr/local/istsos/services \
                && chown -R www-data:www-data /usr/local/istsos/logs \
                && chown -R www-data:www-data /usr/local/istsos/wnslib \
		&& rm ./istsos-2.3.1.tar.gz

COPY ./000-default.conf /etc/apache2/sites-enabled/000-default.conf
	
EXPOSE 80
	
CMD apachectl -D FOREGROUND
```
========================================

and my docker-compose.yaml file like...

========================================
```
version: '2'

services:
  istsos:
    build: .
    ports:
      - 8083:80    
    depends_on:
      - database

  database:
    image: mdillon/postgis:9.3
    environment:
      - POSTGRES_DB=istSOS
      - POSTGRES_USER=istSOS
      - POSTGRES_PASSWORD=ChangeMe
    ports:
      - 5436:5432
    volumes:
      - ./data:/var/lib/postgresql/data
```

========================================

In the Admin UI I can connect successfully to the database and the app status is "up", so it seems everything is running correctly:

![istsosstatus](https://user-images.githubusercontent.com/25749955/48561506-67702d00-e8f0-11e8-8ef0-e5f8efbaea12.JPG)

I can create new services, insert observable properties and offerings with no problems. When I want to create a new procedure, this error is thrown:

![istsoserror](https://user-images.githubusercontent.com/25749955/48561608-98506200-e8f0-11e8-8dfd-946e66820e27.JPG)

I have made sure all the values I entered into the fields contain no special characters, as visible in the screenshot. I checked the apache log files, which don't show any errors. 

Has anyone run into this issue, or have an idea about any possible solution?

Thanks for any advice

Daniel
